#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "NarrativeDialogueManager.generated.h"

// ============================================================
// Narrative & Dialogue Manager — Agent #15
// Dialogue trees for NPC_Elder_Camp, NPC_Scout_Valley,
// NPC_Tracker_River. Integrates with QuestSystemManager.
// ============================================================

UENUM(BlueprintType)
enum class ENarr_DialogueState : uint8
{
    Idle        UMETA(DisplayName = "Idle"),
    Active      UMETA(DisplayName = "Active"),
    Completed   UMETA(DisplayName = "Completed"),
    Locked      UMETA(DisplayName = "Locked")
};

UENUM(BlueprintType)
enum class ENarr_NPCRole : uint8
{
    Elder       UMETA(DisplayName = "Elder"),
    Scout       UMETA(DisplayName = "Scout"),
    Tracker     UMETA(DisplayName = "Tracker"),
    Survivor    UMETA(DisplayName = "Survivor")
};

USTRUCT(BlueprintType)
struct FNarr_DialogueLine
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString LineID;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString SpeakerName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString LineText;

    /** Supabase TTS audio URL — pre-generated by Agent #15 */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString AudioURL;

    /** Duration in seconds for subtitle display */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    float DisplayDuration;

    FNarr_DialogueLine()
        : LineID(TEXT(""))
        , SpeakerName(TEXT(""))
        , LineText(TEXT(""))
        , AudioURL(TEXT(""))
        , DisplayDuration(4.0f)
    {}
};

USTRUCT(BlueprintType)
struct FNarr_DialogueNode
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString NodeID;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    TArray<FNarr_DialogueLine> Lines;

    /** IDs of nodes this node can transition to (player choices) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    TArray<FString> NextNodeIDs;

    /** Quest ID to activate when this node is reached (empty = none) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString ActivatesQuestID;

    /** Quest ID required to unlock this node (empty = always available) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString RequiredQuestID;

    FNarr_DialogueNode()
        : NodeID(TEXT(""))
        , ActivatesQuestID(TEXT(""))
        , RequiredQuestID(TEXT(""))
    {}
};

USTRUCT(BlueprintType)
struct FNarr_DialogueTree
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString TreeID;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString NPCName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    ENarr_NPCRole NPCRole;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString RootNodeID;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    TArray<FNarr_DialogueNode> Nodes;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    ENarr_DialogueState State;

    FNarr_DialogueTree()
        : TreeID(TEXT(""))
        , NPCName(TEXT(""))
        , NPCRole(ENarr_NPCRole::Survivor)
        , RootNodeID(TEXT(""))
        , State(ENarr_DialogueState::Idle)
    {}
};

UCLASS(BlueprintType, Blueprintable)
class TRANSPERSONALGAME_API ANarrativeDialogueManager : public AActor
{
    GENERATED_BODY()

public:
    ANarrativeDialogueManager();

protected:
    virtual void BeginPlay() override;

public:
    virtual void Tick(float DeltaTime) override;

    // ---- Registered Dialogue Trees ----
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    TArray<FNarr_DialogueTree> DialogueTrees;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString ActiveTreeID;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    FString ActiveNodeID;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Narrative")
    int32 ActiveLineIndex;

    // ---- Core Dialogue Functions ----

    /** Start dialogue with a specific NPC tree */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    bool StartDialogue(const FString& TreeID);

    /** Advance to next line in current node */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    bool AdvanceLine();

    /** Choose a branch (player choice index) */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    bool ChooseBranch(int32 ChoiceIndex);

    /** End current dialogue */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    void EndDialogue();

    /** Get current line text for HUD display */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    FString GetCurrentLineText() const;

    /** Get current speaker name */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    FString GetCurrentSpeakerName() const;

    /** Get current audio URL for playback */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    FString GetCurrentAudioURL() const;

    /** Get available player choices at current node */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    TArray<FString> GetCurrentChoices() const;

    /** Register a dialogue tree at runtime */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    void RegisterDialogueTree(const FNarr_DialogueTree& Tree);

    /** Get tree by NPC name */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    FNarr_DialogueTree GetTreeByNPCName(const FString& NPCName) const;

    /** Check if player is currently in dialogue */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    bool IsDialogueActive() const;

    /** Called when player enters a dialogue trigger zone */
    UFUNCTION(BlueprintCallable, Category = "Narrative")
    void OnPlayerEnterDialogueZone(const FString& ZoneID);

private:
    void InitializeDefaultDialogueTrees();
    FNarr_DialogueTree BuildElderTree();
    FNarr_DialogueTree BuildScoutTree();
    FNarr_DialogueTree BuildTrackerTree();

    FNarr_DialogueNode* FindNode(FNarr_DialogueTree& Tree, const FString& NodeID);
    const FNarr_DialogueNode* FindNodeConst(const FNarr_DialogueTree& Tree, const FString& NodeID) const;
    FNarr_DialogueTree* FindTree(const FString& TreeID);
    const FNarr_DialogueTree* FindTreeConst(const FString& TreeID) const;
};
