// QuestNarrativeData.cpp
// Agent #15 — Narrative & Dialogue Agent
// Full narrative dialogue for the 3 core quests in MinPlayableMap:
//   1. Hunt: Raptor Pack  (trigger at 800, 200, 100)
//   2. Gather: Flint      (trigger at -600, 500, 80)
//   3. Defend: Camp       (trigger at 0, -800, 90)
// Audio URLs reference ElevenLabs TTS assets on Supabase Storage.

#include "QuestNarrativeData.h"

// ─── Audio URLs (Supabase Storage) ───────────────────────────────────────────
// Generated by Agent #15 via ElevenLabs TTS in cycles 009-011

// Cycle 011 — Hunt briefing
static const FString URL_Hunt_Briefing =
    TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782751147011_Elder_QuestBriefing_Hunt.mp3");

// Cycle 011 — Gather briefing
static const FString URL_Gather_Briefing =
    TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782751149998_Elder_QuestBriefing_Gather.mp3");

// Cycle 011 — Defend briefing
static const FString URL_Defend_Briefing =
    TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782751169995_Elder_QuestBriefing_Defend.mp3");

// Cycle 010 — Quest reward / completion
static const FString URL_Hunt_Completion =
    TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782751047860_QuestReward_Elder.mp3");

// Cycle 009 — Crafting / tool lines (reused for Gather completion)
static const FString URL_Gather_Completion =
    TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782751031042_TrackingNPC_Elder.mp3");

// ─── Constructor ─────────────────────────────────────────────────────────────

UNarr_QuestNarrativeData::UNarr_QuestNarrativeData()
{
    // ── QUEST 1: Hunt — Raptor Pack ──────────────────────────────────────────
    {
        FNarr_QuestDialogue HuntDialogue;
        HuntDialogue.QuestID = ENarr_QuestID::Hunt_RaptorPack;

        // Briefing — Elder warns player at trigger volume (800, 200, 100)
        HuntDialogue.BriefingLines.Add(FNarr_DialogueLine(
            TEXT("Elder Kara"),
            TEXT("The raptor pack circles at dusk. Three of them — young males, hungry and bold. "
                 "You have one chance to drive them off before they reach the camp. "
                 "Use fire. They fear it. Move fast, and do not let them flank you."),
            URL_Hunt_Briefing,
            8.0f
        ));

        // Progress — Scout reports mid-hunt
        HuntDialogue.ProgressLines.Add(FNarr_DialogueLine(
            TEXT("Scout"),
            TEXT("Two raptors spotted near the northern tree line. The third is circling wide — watch your back."),
            TEXT(""),  // No TTS yet — Audio Agent (#16) to generate
            5.0f
        ));

        // Completion — Elder acknowledges success
        HuntDialogue.CompletionLines.Add(FNarr_DialogueLine(
            TEXT("Elder Kara"),
            TEXT("You did it. The raptor pack is gone — driven off by the fire. "
                 "The tribe is safe tonight. Take these hides. You earned them."),
            URL_Hunt_Completion,
            7.0f
        ));

        // Failure — Elder if player retreats or dies
        HuntDialogue.FailureLines.Add(FNarr_DialogueLine(
            TEXT("Elder Kara"),
            TEXT("They broke through. Three hunters wounded. We cannot afford another night like this. "
                 "Rest. Then we try again."),
            TEXT(""),
            6.0f
        ));

        AllQuestDialogues.Add(HuntDialogue);
    }

    // ── QUEST 2: Gather — Flint ──────────────────────────────────────────────
    {
        FNarr_QuestDialogue GatherDialogue;
        GatherDialogue.QuestID = ENarr_QuestID::Gather_Flint;

        // Briefing — Elder sends player to river bend
        GatherDialogue.BriefingLines.Add(FNarr_DialogueLine(
            TEXT("Elder Kara"),
            TEXT("Flint. Sharp flint from the river bend. Without it, we cannot make blades, "
                 "we cannot scrape hides, we cannot survive the cold season. "
                 "Bring back what you can carry. The river is two ridges east — "
                 "watch for the big predators near the water."),
            URL_Gather_Briefing,
            9.0f
        ));

        // Progress — Player finds partial flint deposit
        GatherDialogue.ProgressLines.Add(FNarr_DialogueLine(
            TEXT("Player (internal)"),
            TEXT("Good flint here. The edges are sharp enough. Need more — keep searching the riverbank."),
            TEXT(""),
            4.0f
        ));

        // Completion — Elder receives the flint
        GatherDialogue.CompletionLines.Add(FNarr_DialogueLine(
            TEXT("Elder Kara"),
            TEXT("This is good stone. We can make six blades from this — maybe eight if the knapper is careful. "
                 "You did well. The tribe will eat tonight because of this."),
            URL_Gather_Completion,
            7.0f
        ));

        // Failure — Player returns with too little
        GatherDialogue.FailureLines.Add(FNarr_DialogueLine(
            TEXT("Elder Kara"),
            TEXT("Not enough. We need at least ten good pieces to last the season. "
                 "Go back when you are ready. The river will still be there."),
            TEXT(""),
            5.0f
        ));

        AllQuestDialogues.Add(GatherDialogue);
    }

    // ── QUEST 3: Defend — Camp ───────────────────────────────────────────────
    {
        FNarr_QuestDialogue DefendDialogue;
        DefendDialogue.QuestID = ENarr_QuestID::Defend_Camp;

        // Briefing — Elder describes the threat
        DefendDialogue.BriefingLines.Add(FNarr_DialogueLine(
            TEXT("Elder Kara"),
            TEXT("They came in the night. Twelve of them — armed with bone clubs and fire. "
                 "We held the eastern wall but lost two hunters. The camp stands. Barely. "
                 "If they come again, we will not be so lucky. "
                 "We need more defenders, and we need them now."),
            URL_Defend_Briefing,
            10.0f
        ));

        // Progress — Hunter reports wave incoming
        DefendDialogue.ProgressLines.Add(FNarr_DialogueLine(
            TEXT("Hunter Brek"),
            TEXT("Second wave coming from the south! More of them this time — at least twenty. "
                 "Hold the fire line! Do not let them past the torches!"),
            TEXT(""),
            5.0f
        ));

        // Completion — Camp secured
        DefendDialogue.CompletionLines.Add(FNarr_DialogueLine(
            TEXT("Elder Kara"),
            TEXT("The camp holds. They will not come back — not after what you did tonight. "
                 "You are one of us now. A defender of this tribe."),
            TEXT(""),
            6.0f
        ));

        // Failure — Camp overrun
        DefendDialogue.FailureLines.Add(FNarr_DialogueLine(
            TEXT("Elder Kara"),
            TEXT("The eastern wall is gone. We must fall back to the caves. "
                 "Gather what you can carry. We move at first light."),
            TEXT(""),
            6.0f
        ));

        AllQuestDialogues.Add(DefendDialogue);
    }
}

// ─── Methods ─────────────────────────────────────────────────────────────────

FNarr_QuestDialogue UNarr_QuestNarrativeData::GetQuestDialogue(ENarr_QuestID QuestID) const
{
    for (const FNarr_QuestDialogue& Dialogue : AllQuestDialogues)
    {
        if (Dialogue.QuestID == QuestID)
        {
            return Dialogue;
        }
    }
    return FNarr_QuestDialogue();
}

TArray<FNarr_DialogueLine> UNarr_QuestNarrativeData::GetBriefingLines(ENarr_QuestID QuestID) const
{
    FNarr_QuestDialogue Dialogue = GetQuestDialogue(QuestID);
    return Dialogue.BriefingLines;
}

TArray<FNarr_DialogueLine> UNarr_QuestNarrativeData::GetCompletionLines(ENarr_QuestID QuestID) const
{
    FNarr_QuestDialogue Dialogue = GetQuestDialogue(QuestID);
    return Dialogue.CompletionLines;
}
