#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "Engine/DataTable.h"
#include "Build_FinalCycleReport.generated.h"

UENUM(BlueprintType)
enum class EBuild_CycleCompletionStatus : uint8
{
    InProgress,
    Completed,
    Failed,
    Critical,
    Delivered
};

UENUM(BlueprintType)
enum class EBuild_AgentStatus : uint8
{
    NotStarted,
    InProgress,
    Completed,
    Failed,
    Timeout
};

USTRUCT(BlueprintType)
struct TRANSPERSONALGAME_API FBuild_AgentExecutionResult
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadOnly, Category = "Agent Execution")
    int32 AgentNumber;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Execution")
    FString AgentName;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Execution")
    EBuild_AgentStatus Status;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Execution")
    int32 ToolCallsExecuted;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Execution")
    int32 FilesWritten;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Execution")
    int32 UE5CommandsExecuted;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Execution")
    float ExecutionTimeSeconds;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Execution")
    FString LastError;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Execution")
    TArray<FString> DeliverablesCreated;

    FBuild_AgentExecutionResult()
    {
        AgentNumber = 0;
        AgentName = TEXT("");
        Status = EBuild_AgentStatus::NotStarted;
        ToolCallsExecuted = 0;
        FilesWritten = 0;
        UE5CommandsExecuted = 0;
        ExecutionTimeSeconds = 0.0f;
        LastError = TEXT("");
    }
};

USTRUCT(BlueprintType)
struct TRANSPERSONALGAME_API FBuild_SystemIntegrationStatus
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadOnly, Category = "System Integration")
    FString SystemName;

    UPROPERTY(BlueprintReadOnly, Category = "System Integration")
    bool bIsLoaded;

    UPROPERTY(BlueprintReadOnly, Category = "System Integration")
    bool bIsFunctional;

    UPROPERTY(BlueprintReadOnly, Category = "System Integration")
    bool bHasValidDependencies;

    UPROPERTY(BlueprintReadOnly, Category = "System Integration")
    int32 ComponentCount;

    UPROPERTY(BlueprintReadOnly, Category = "System Integration")
    FString IntegrationNotes;

    FBuild_SystemIntegrationStatus()
    {
        SystemName = TEXT("");
        bIsLoaded = false;
        bIsFunctional = false;
        bHasValidDependencies = false;
        ComponentCount = 0;
        IntegrationNotes = TEXT("");
    }
};

USTRUCT(BlueprintType)
struct TRANSPERSONALGAME_API FBuild_QualityMetrics
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadOnly, Category = "Quality Metrics")
    int32 TotalClassesLoaded;

    UPROPERTY(BlueprintReadOnly, Category = "Quality Metrics")
    int32 FunctionalTestsPassed;

    UPROPERTY(BlueprintReadOnly, Category = "Quality Metrics")
    int32 IntegrationTestsPassed;

    UPROPERTY(BlueprintReadOnly, Category = "Quality Metrics")
    float CompilationSuccessRate;

    UPROPERTY(BlueprintReadOnly, Category = "Quality Metrics")
    float SystemIntegrationRate;

    UPROPERTY(BlueprintReadOnly, Category = "Quality Metrics")
    int32 CriticalErrorsFound;

    UPROPERTY(BlueprintReadOnly, Category = "Quality Metrics")
    int32 WarningsFound;

    FBuild_QualityMetrics()
    {
        TotalClassesLoaded = 0;
        FunctionalTestsPassed = 0;
        IntegrationTestsPassed = 0;
        CompilationSuccessRate = 0.0f;
        SystemIntegrationRate = 0.0f;
        CriticalErrorsFound = 0;
        WarningsFound = 0;
    }
};

/**
 * Final Cycle Report - Comprehensive summary of production cycle completion
 * Generated by Integration Agent #19 at the end of each cycle
 */
USTRUCT(BlueprintType)
struct TRANSPERSONALGAME_API FBuild_FinalCycleReport
{
    GENERATED_BODY()

    // Cycle identification
    UPROPERTY(BlueprintReadOnly, Category = "Cycle Info")
    FString CycleID;

    UPROPERTY(BlueprintReadOnly, Category = "Cycle Info")
    FDateTime CycleStartTime;

    UPROPERTY(BlueprintReadOnly, Category = "Cycle Info")
    FDateTime CycleEndTime;

    UPROPERTY(BlueprintReadOnly, Category = "Cycle Info")
    float TotalCycleDurationMinutes;

    // Overall status
    UPROPERTY(BlueprintReadOnly, Category = "Status")
    EBuild_CycleCompletionStatus OverallStatus;

    UPROPERTY(BlueprintReadOnly, Category = "Status")
    float CycleCompletionPercentage;

    UPROPERTY(BlueprintReadOnly, Category = "Status")
    bool bReadyForNextCycle;

    // Agent execution results
    UPROPERTY(BlueprintReadOnly, Category = "Agent Results")
    TArray<FBuild_AgentExecutionResult> AgentResults;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Results")
    int32 AgentsCompleted;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Results")
    int32 AgentsFailed;

    UPROPERTY(BlueprintReadOnly, Category = "Agent Results")
    int32 AgentsTimedOut;

    // System integration status
    UPROPERTY(BlueprintReadOnly, Category = "Integration")
    TArray<FBuild_SystemIntegrationStatus> SystemStatuses;

    UPROPERTY(BlueprintReadOnly, Category = "Integration")
    int32 SystemsIntegrated;

    UPROPERTY(BlueprintReadOnly, Category = "Integration")
    int32 SystemsTotal;

    // Quality metrics
    UPROPERTY(BlueprintReadOnly, Category = "Quality")
    FBuild_QualityMetrics QualityMetrics;

    // Production metrics
    UPROPERTY(BlueprintReadOnly, Category = "Production")
    int32 TotalFilesCreated;

    UPROPERTY(BlueprintReadOnly, Category = "Production")
    int32 TotalUE5CommandsExecuted;

    UPROPERTY(BlueprintReadOnly, Category = "Production")
    int32 TotalToolCallsExecuted;

    // Critical issues
    UPROPERTY(BlueprintReadOnly, Category = "Issues")
    TArray<FString> CriticalIssues;

    UPROPERTY(BlueprintReadOnly, Category = "Issues")
    TArray<FString> RecommendationsForNextCycle;

    // Summary
    UPROPERTY(BlueprintReadOnly, Category = "Summary")
    FString ExecutiveSummary;

    UPROPERTY(BlueprintReadOnly, Category = "Summary")
    FString NextCyclePriorities;

    FBuild_FinalCycleReport()
    {
        CycleID = TEXT("");
        CycleStartTime = FDateTime::Now();
        CycleEndTime = FDateTime::Now();
        TotalCycleDurationMinutes = 0.0f;
        OverallStatus = EBuild_CycleCompletionStatus::InProgress;
        CycleCompletionPercentage = 0.0f;
        bReadyForNextCycle = false;
        AgentsCompleted = 0;
        AgentsFailed = 0;
        AgentsTimedOut = 0;
        SystemsIntegrated = 0;
        SystemsTotal = 0;
        TotalFilesCreated = 0;
        TotalUE5CommandsExecuted = 0;
        TotalToolCallsExecuted = 0;
        ExecutiveSummary = TEXT("");
        NextCyclePriorities = TEXT("");
    }
};

/**
 * Data table row for cycle history tracking
 */
USTRUCT(BlueprintType)
struct TRANSPERSONALGAME_API FBuild_CycleHistoryEntry : public FTableRowBase
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Cycle History")
    FBuild_FinalCycleReport CycleReport;

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Cycle History")
    bool bWasSuccessful;

    UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Cycle History")
    FString CycleNotes;

    FBuild_CycleHistoryEntry()
    {
        bWasSuccessful = false;
        CycleNotes = TEXT("");
    }
};