#include "Audio_VoicelineIntegration.h"
#include "Engine/Engine.h"
#include "Engine/World.h"
#include "Components/AudioComponent.h"
#include "Sound/SoundCue.h"
#include "TimerManager.h"
#include "Kismet/GameplayStatics.h"

UAudio_VoicelineIntegration::UAudio_VoicelineIntegration()
{
    PrimaryComponentTick.bCanEverTick = false;
    
    MasterVoicelineVolume = 1.0f;
    bVoicelinesEnabled = true;
    MinTimeBetweenVoicelines = 5.0f;
    LastVoicelineTime = 0.0f;
    
    VoicelineAudioComponent = nullptr;
}

void UAudio_VoicelineIntegration::BeginPlay()
{
    Super::BeginPlay();
    
    InitializeVoicelineSystem();
    LoadPresetVoicelines();
}

void UAudio_VoicelineIntegration::InitializeVoicelineSystem()
{
    // Create audio component for voiceline playback
    if (!VoicelineAudioComponent)
    {
        VoicelineAudioComponent = NewObject<UAudioComponent>(this);
        if (VoicelineAudioComponent)
        {
            VoicelineAudioComponent->SetVolumeMultiplier(MasterVoicelineVolume);
            VoicelineAudioComponent->bAutoActivate = false;
            VoicelineAudioComponent->AttachToComponent(GetOwner()->GetRootComponent(), 
                FAttachmentTransformRules::KeepRelativeTransform);
        }
    }
    
    // Initialize cooldown tracking
    TriggerCooldowns.Empty();
    for (int32 i = 0; i < (int32)EAudio_VoicelineTrigger::OnSurvival + 1; ++i)
    {
        EAudio_VoicelineTrigger TriggerType = (EAudio_VoicelineTrigger)i;
        TriggerCooldowns.Add(TriggerType, 0.0f);
    }
    
    UE_LOG(LogTemp, Log, TEXT("Audio_VoicelineIntegration: System initialized"));
}

void UAudio_VoicelineIntegration::LoadPresetVoicelines()
{
    // Load the voice lines generated by the text-to-speech system
    FAudio_VoicelineData AtmosphericNarrator;
    AtmosphericNarrator.VoicelineText = TEXT("The forest holds its breath. Ancient predators move through these lands, their footsteps echoing like thunder. Stay alert, survivor.");
    AtmosphericNarrator.AudioURL = TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1777683792231_AtmosphericNarrator.mp3");
    AtmosphericNarrator.VoicelineType = EAudio_VoicelineType::AtmosphericNarrator;
    AtmosphericNarrator.TriggerType = EAudio_VoicelineTrigger::OnPlayerSpawn;
    AtmosphericNarrator.Duration = 9.0f;
    AtmosphericNarrator.CooldownTime = 60.0f;
    AtmosphericNarrator.bIsContextual = true;
    VoicelineDatabase.Add(AtmosphericNarrator);
    
    FAudio_VoicelineData SurvivalExpert;
    SurvivalExpert.VoicelineText = TEXT("Listen carefully. The T-Rex approaches from the north. Its massive footsteps shake the ground. Find cover immediately.");
    SurvivalExpert.AudioURL = TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1777683793958_SurvivalExpert.mp3");
    SurvivalExpert.VoicelineType = EAudio_VoicelineType::SurvivalExpert;
    SurvivalExpert.TriggerType = EAudio_VoicelineTrigger::OnDinosaurSighting;
    SurvivalExpert.Duration = 8.0f;
    SurvivalExpert.CooldownTime = 45.0f;
    SurvivalExpert.bIsContextual = true;
    VoicelineDatabase.Add(SurvivalExpert);
    
    // Add previous voice lines from Narrative Agent
    FAudio_VoicelineData SurvivalNarrator;
    SurvivalNarrator.VoicelineText = TEXT("The massive footprints in the mud tell a story of terror...");
    SurvivalNarrator.VoicelineType = EAudio_VoicelineType::AtmosphericNarrator;
    SurvivalNarrator.TriggerType = EAudio_VoicelineTrigger::OnDiscovery;
    SurvivalNarrator.Duration = 15.0f;
    SurvivalNarrator.CooldownTime = 90.0f;
    VoicelineDatabase.Add(SurvivalNarrator);
    
    FAudio_VoicelineData PlayerCharacter;
    PlayerCharacter.VoicelineText = TEXT("My heart pounds as I hear the distant roar echoing through the valley...");
    PlayerCharacter.VoicelineType = EAudio_VoicelineType::PlayerThought;
    PlayerCharacter.TriggerType = EAudio_VoicelineTrigger::OnDanger;
    PlayerCharacter.Duration = 15.0f;
    PlayerCharacter.CooldownTime = 30.0f;
    VoicelineDatabase.Add(PlayerCharacter);
    
    UE_LOG(LogTemp, Log, TEXT("Audio_VoicelineIntegration: Loaded %d preset voicelines"), VoicelineDatabase.Num());
}

void UAudio_VoicelineIntegration::TriggerVoiceline(EAudio_VoicelineTrigger TriggerType, const FVector& Location)
{
    if (!bVoicelinesEnabled || !CanTriggerVoiceline(TriggerType))
    {
        return;
    }
    
    FAudio_VoicelineData SelectedVoiceline = GetRandomVoicelineByTrigger(TriggerType);
    if (!SelectedVoiceline.VoicelineText.IsEmpty())
    {
        PlayVoicelineInternal(SelectedVoiceline, Location);
        
        // Update cooldown
        TriggerCooldowns[TriggerType] = GetWorld()->GetTimeSeconds() + SelectedVoiceline.CooldownTime;
        LastVoicelineTime = GetWorld()->GetTimeSeconds();
        
        UE_LOG(LogTemp, Log, TEXT("Audio_VoicelineIntegration: Triggered %s voiceline"), 
            *UEnum::GetValueAsString(TriggerType));
    }
}

void UAudio_VoicelineIntegration::PlayVoicelineByType(EAudio_VoicelineType VoicelineType, const FVector& Location)
{
    if (!bVoicelinesEnabled)
    {
        return;
    }
    
    for (const FAudio_VoicelineData& Voiceline : VoicelineDatabase)
    {
        if (Voiceline.VoicelineType == VoicelineType)
        {
            PlayVoicelineInternal(Voiceline, Location);
            LastVoicelineTime = GetWorld()->GetTimeSeconds();
            break;
        }
    }
}

void UAudio_VoicelineIntegration::PlayVoicelineInternal(const FAudio_VoicelineData& VoicelineData, const FVector& Location)
{
    if (!VoicelineAudioComponent)
    {
        UE_LOG(LogTemp, Warning, TEXT("Audio_VoicelineIntegration: No audio component available"));
        return;
    }
    
    // Stop any currently playing voiceline
    StopCurrentVoiceline();
    
    // For now, we'll use a placeholder sound since we can't directly load from URL
    // In a full implementation, this would load the audio from the URL
    UE_LOG(LogTemp, Log, TEXT("Audio_VoicelineIntegration: Playing voiceline: %s"), 
        *VoicelineData.VoicelineText);
    UE_LOG(LogTemp, Log, TEXT("Audio_VoicelineIntegration: Audio URL: %s"), 
        *VoicelineData.AudioURL);
    
    // Set timer to call OnVoicelineFinished after the duration
    GetWorld()->GetTimerManager().SetTimer(VoicelineTimerHandle, 
        this, &UAudio_VoicelineIntegration::OnVoicelineFinished, 
        VoicelineData.Duration, false);
}

void UAudio_VoicelineIntegration::StopCurrentVoiceline()
{
    if (VoicelineAudioComponent && VoicelineAudioComponent->IsPlaying())
    {
        VoicelineAudioComponent->Stop();
    }
    
    GetWorld()->GetTimerManager().ClearTimer(VoicelineTimerHandle);
}

bool UAudio_VoicelineIntegration::CanTriggerVoiceline(EAudio_VoicelineTrigger TriggerType) const
{
    float CurrentTime = GetWorld()->GetTimeSeconds();
    
    // Check global cooldown
    if (CurrentTime - LastVoicelineTime < MinTimeBetweenVoicelines)
    {
        return false;
    }
    
    // Check specific trigger cooldown
    if (TriggerCooldowns.Contains(TriggerType))
    {
        return CurrentTime >= TriggerCooldowns[TriggerType];
    }
    
    return true;
}

void UAudio_VoicelineIntegration::SetVoicelineVolume(float Volume)
{
    MasterVoicelineVolume = FMath::Clamp(Volume, 0.0f, 1.0f);
    
    if (VoicelineAudioComponent)
    {
        VoicelineAudioComponent->SetVolumeMultiplier(MasterVoicelineVolume);
    }
}

void UAudio_VoicelineIntegration::EnableVoicelines(bool bEnabled)
{
    bVoicelinesEnabled = bEnabled;
    
    if (!bEnabled)
    {
        StopCurrentVoiceline();
    }
}

FAudio_VoicelineData UAudio_VoicelineIntegration::GetRandomVoicelineByTrigger(EAudio_VoicelineTrigger TriggerType) const
{
    TArray<FAudio_VoicelineData> MatchingVoicelines;
    
    for (const FAudio_VoicelineData& Voiceline : VoicelineDatabase)
    {
        if (Voiceline.TriggerType == TriggerType)
        {
            MatchingVoicelines.Add(Voiceline);
        }
    }
    
    if (MatchingVoicelines.Num() > 0)
    {
        int32 RandomIndex = FMath::RandRange(0, MatchingVoicelines.Num() - 1);
        return MatchingVoicelines[RandomIndex];
    }
    
    return FAudio_VoicelineData();
}

void UAudio_VoicelineIntegration::AddVoicelineToDatabase(const FAudio_VoicelineData& NewVoiceline)
{
    VoicelineDatabase.Add(NewVoiceline);
    UE_LOG(LogTemp, Log, TEXT("Audio_VoicelineIntegration: Added new voiceline to database"));
}

void UAudio_VoicelineIntegration::LoadVoicelinesFromNarrativeSystem()
{
    // This would integrate with the Narrative Agent's voice line system
    // For now, we use the preset voicelines loaded in LoadPresetVoicelines()
    UE_LOG(LogTemp, Log, TEXT("Audio_VoicelineIntegration: Loading voicelines from narrative system"));
}

void UAudio_VoicelineIntegration::OnVoicelineFinished()
{
    UE_LOG(LogTemp, Log, TEXT("Audio_VoicelineIntegration: Voiceline playback finished"));
    
    // Clear the timer
    GetWorld()->GetTimerManager().ClearTimer(VoicelineTimerHandle);
}

void UAudio_VoicelineIntegration::UpdateCooldowns()
{
    // This is called internally to manage cooldowns
    // The actual cooldown checking is done in CanTriggerVoiceline()
}