// AudioZoneSystem.cpp — Agent #16 Audio Agent
// Adaptive audio zone system for prehistoric survival game.
// Manages ambient sound blending, danger-level response, and TTS dialogue integration.

#include "AudioZoneSystem.h"
#include "Engine/World.h"
#include "GameFramework/Actor.h"
#include "Math/UnrealMathUtility.h"

UAudio_ZoneSystem::UAudio_ZoneSystem()
{
    PrimaryComponentTick.bCanEverTick = true;
    PrimaryComponentTick.TickInterval = TickInterval;

    // Default zone config
    ZoneConfig.ZoneType = EAudio_ZoneType::Jungle;
    ZoneConfig.BlendRadius = 1000.0f;
    ZoneConfig.MaxVolume = 1.0f;
    ZoneConfig.FadeInTime = 2.0f;
    ZoneConfig.FadeOutTime = 3.0f;
    ZoneConfig.bLooping = true;

    // Campfire Freesound IDs (from Agent #16 search results)
    ZoneConfig.FreesoundIDs = { 819666, 856943, 790790 };
}

void UAudio_ZoneSystem::BeginPlay()
{
    Super::BeginPlay();
    SeedDefaultAudioURLs();
    CurrentVolume = 0.0f;
    TargetVolume = 0.0f;
}

void UAudio_ZoneSystem::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
    Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

    TickAccumulator += DeltaTime;
    if (TickAccumulator < TickInterval)
    {
        return;
    }
    TickAccumulator = 0.0f;

    // Smooth volume towards target using simple lerp
    float FadeSpeed = bPlayerInZone
        ? (1.0f / FMath::Max(ZoneConfig.FadeInTime, 0.01f))
        : (1.0f / FMath::Max(ZoneConfig.FadeOutTime, 0.01f));

    float DangerMult = GetDangerVolumeMultiplier();
    float FinalTarget = TargetVolume * DangerMult;

    CurrentVolume = FMath::FInterpTo(CurrentVolume, FinalTarget, TickInterval, FadeSpeed * 5.0f);
    CurrentVolume = FMath::Clamp(CurrentVolume, 0.0f, ZoneConfig.MaxVolume);
}

void UAudio_ZoneSystem::OnPlayerEnterZone()
{
    bPlayerInZone = true;
    TargetVolume = ZoneConfig.MaxVolume;
    UE_LOG(LogTemp, Log, TEXT("AudioZone: Player entered zone [%s]"), *GetZoneTypeString());
}

void UAudio_ZoneSystem::OnPlayerExitZone()
{
    bPlayerInZone = false;
    TargetVolume = 0.0f;
    UE_LOG(LogTemp, Log, TEXT("AudioZone: Player exited zone [%s]"), *GetZoneTypeString());
}

void UAudio_ZoneSystem::SetDangerLevel(EAudio_DangerLevel NewLevel)
{
    if (CurrentDangerLevel != NewLevel)
    {
        CurrentDangerLevel = NewLevel;
        UE_LOG(LogTemp, Log, TEXT("AudioZone: Danger level changed to [%d] in zone [%s]"),
            (int32)NewLevel, *GetZoneTypeString());
    }
}

FString UAudio_ZoneSystem::GetZoneTypeString() const
{
    switch (ZoneConfig.ZoneType)
    {
        case EAudio_ZoneType::Jungle:       return TEXT("Jungle");
        case EAudio_ZoneType::Campfire:     return TEXT("Campfire");
        case EAudio_ZoneType::TRexDanger:   return TEXT("TRex_Danger");
        case EAudio_ZoneType::River:        return TEXT("River");
        case EAudio_ZoneType::Cave:         return TEXT("Cave");
        case EAudio_ZoneType::OpenPlain:    return TEXT("OpenPlain");
        case EAudio_ZoneType::NightTime:    return TEXT("NightTime");
        case EAudio_ZoneType::Storm:        return TEXT("Storm");
        default:                            return TEXT("Unknown");
    }
}

float UAudio_ZoneSystem::GetDangerVolumeMultiplier() const
{
    // Danger level modulates ambient volume:
    // Safe → full jungle ambience, low tension music
    // Danger/Critical → suppress ambient, boost heartbeat/danger stings
    switch (CurrentDangerLevel)
    {
        case EAudio_DangerLevel::Safe:      return 1.0f;
        case EAudio_DangerLevel::Caution:   return 0.75f;
        case EAudio_DangerLevel::Danger:    return 0.4f;
        case EAudio_DangerLevel::Critical:  return 0.1f;
        default:                            return 1.0f;
    }
}

void UAudio_ZoneSystem::RegisterDialogueLine(const FString& Speaker, const FString& Text, const FString& AudioURL, float Duration)
{
    FAudio_DialogueEntry Entry;
    Entry.SpeakerName = Speaker;
    Entry.DialogueText = Text;
    Entry.AudioURL = AudioURL;
    Entry.Duration = Duration;
    Entry.bHasBeenPlayed = false;
    DialogueEntries.Add(Entry);
    UE_LOG(LogTemp, Log, TEXT("AudioZone: Registered dialogue line for [%s]"), *Speaker);
}

bool UAudio_ZoneSystem::GetNextDialogueLine(FAudio_DialogueEntry& OutEntry)
{
    for (FAudio_DialogueEntry& Entry : DialogueEntries)
    {
        if (!Entry.bHasBeenPlayed)
        {
            OutEntry = Entry;
            return true;
        }
    }
    return false;
}

void UAudio_ZoneSystem::MarkDialoguePlayed(const FString& Speaker)
{
    for (FAudio_DialogueEntry& Entry : DialogueEntries)
    {
        if (Entry.SpeakerName == Speaker && !Entry.bHasBeenPlayed)
        {
            Entry.bHasBeenPlayed = true;
            UE_LOG(LogTemp, Log, TEXT("AudioZone: Marked dialogue played for [%s]"), *Speaker);
            return;
        }
    }
}

void UAudio_ZoneSystem::SeedDefaultAudioURLs()
{
    // TTS audio URLs generated by Agent #16 in PROD_CYCLE_AUTO_20260626_006
    JungleNarrationURL = TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782469187596_Narrator_Jungle_Ambience.mp3");
    CombatWarningURL   = TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782469196131_Kael_Combat_Warning.mp3");

    // Register dialogue lines from Agent #15 TTS outputs (PROD_CYCLE_AUTO_20260626_006)
    RegisterDialogueLine(
        TEXT("Narrator"),
        TEXT("The jungle never goes quiet. That is how you know something is wrong."),
        JungleNarrationURL,
        15.0f
    );
    RegisterDialogueLine(
        TEXT("Kael"),
        TEXT("Run. Do not look back. Do not stop to fight."),
        CombatWarningURL,
        9.0f
    );
    // Agent #15 TTS lines
    RegisterDialogueLine(
        TEXT("Kael"),
        TEXT("We lost the eastern camp three nights ago. The ground shook before dawn."),
        TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782469054495_Kael_Survivor.mp3"),
        12.0f
    );
    RegisterDialogueLine(
        TEXT("Mira"),
        TEXT("The river is low. That means the big ones are moving upstream."),
        TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782469057365_Mira_Scout.mp3"),
        11.0f
    );
    RegisterDialogueLine(
        TEXT("Elder Oru"),
        TEXT("The big ones do not hunt at midday. That is our window."),
        TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782469087849_Elder_Oru.mp3"),
        10.0f
    );
    RegisterDialogueLine(
        TEXT("Dara"),
        TEXT("I tracked it for four days. A Triceratops — old one, scarred flank."),
        TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782469091133_Dara_Tracker.mp3"),
        11.0f
    );

    UE_LOG(LogTemp, Log, TEXT("AudioZone: Seeded %d default dialogue entries"), DialogueEntries.Num());
}
