#include "PrehistoricAudioSystem.h"
#include "Components/AudioComponent.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"
#include "GameFramework/Pawn.h"

// ============================================================
// APrehistoricAudioSystem — Implementation
// Adaptive audio for prehistoric survival game.
// Walter Murch principle: silence before the T-Rex is the
// most terrifying sound in the game.
// ============================================================

APrehistoricAudioSystem::APrehistoricAudioSystem()
{
    PrimaryActorTick.bCanEverTick = true;
    PrimaryActorTick.TickInterval = 0.1f; // 10Hz tick — audio doesn't need 60Hz

    // Ambient audio component — jungle/environment layers
    AmbientAudioComponent = CreateDefaultSubobject<UAudioComponent>(TEXT("AmbientAudio"));
    AmbientAudioComponent->SetupAttachment(RootComponent);
    AmbientAudioComponent->bAutoActivate = false;
    AmbientAudioComponent->VolumeMultiplier = 1.0f;

    // Danger audio component — music stingers, tension layers
    DangerAudioComponent = CreateDefaultSubobject<UAudioComponent>(TEXT("DangerAudio"));
    DangerAudioComponent->SetupAttachment(RootComponent);
    DangerAudioComponent->bAutoActivate = false;
    DangerAudioComponent->VolumeMultiplier = 0.0f; // starts silent

    // Voice audio component — survivor narration lines
    VoiceAudioComponent = CreateDefaultSubobject<UAudioComponent>(TEXT("VoiceAudio"));
    VoiceAudioComponent->SetupAttachment(RootComponent);
    VoiceAudioComponent->bAutoActivate = false;

    // Pre-populate voice lines from ElevenLabs TTS (generated by Audio Agent #16)
    // These URLs are from Supabase Storage — loaded at runtime
    FAudio_VoiceLine NightWarning;
    NightWarning.LineID = TEXT("night_warning");
    NightWarning.AudioURL = TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782523071356_Survivor_NightWarning.mp3");
    NightWarning.Subtitle = TEXT("Night is the most dangerous time. Keep the fire burning. Never let it die.");
    NightWarning.Duration = 15.0f;
    SurvivorVoiceLines.Add(NightWarning);

    FAudio_VoiceLine WaterWarning;
    WaterWarning.LineID = TEXT("water_warning");
    WaterWarning.AudioURL = TEXT("https://thdlkizjbpwdndtggleb.supabase.co/storage/v1/object/public/game-assets/tts/1782523079223_Survivor_WaterWarning.mp3");
    WaterWarning.Subtitle = TEXT("The watering holes are shared. If the birds stop singing, something large is already there.");
    WaterWarning.Duration = 18.0f;
    SurvivorVoiceLines.Add(WaterWarning);
}

void APrehistoricAudioSystem::BeginPlay()
{
    Super::BeginPlay();

    // Start ambient audio system
    if (AmbientAudioComponent)
    {
        AmbientAudioComponent->Activate();
    }

    UE_LOG(LogTemp, Log, TEXT("PrehistoricAudioSystem: Initialized. Danger=%d, Biome=%d, Time=%d"),
        (int32)CurrentDangerLevel, (int32)CurrentBiome, (int32)CurrentTimeOfDay);
}

void APrehistoricAudioSystem::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    // Update silence window timer
    if (bInSilenceWindow)
    {
        SilenceWindowTimer -= DeltaTime;
        if (SilenceWindowTimer <= 0.0f)
        {
            bInSilenceWindow = false;
            SilenceWindowTimer = 0.0f;
        }
    }

    // Update danger stinger cooldown
    if (DangerStingerCooldown > 0.0f)
    {
        DangerStingerCooldown -= DeltaTime;
    }

    // Throttled ambient update
    AmbientUpdateTimer += DeltaTime;
    if (AmbientUpdateTimer >= AmbientUpdateInterval)
    {
        AmbientUpdateTimer = 0.0f;
        UpdateDangerFromProximity(AmbientUpdateInterval);
        UpdateAmbientLayers(AmbientUpdateInterval);
    }

    // Blend music layers every tick for smooth transitions
    BlendMusicLayers(DeltaTime);
}

void APrehistoricAudioSystem::UpdateDangerFromProximity(float DeltaTime)
{
    UWorld* World = GetWorld();
    if (!World) return;

    APawn* PlayerPawn = UGameplayStatics::GetPlayerPawn(World, 0);
    if (!PlayerPawn) return;

    FVector PlayerLocation = PlayerPawn->GetActorLocation();
    float ClosestDino = 99999.0f;

    // Scan all actors for dinosaur pawns
    TArray<AActor*> AllActors;
    UGameplayStatics::GetAllActorsOfClass(World, APawn::StaticClass(), AllActors);

    for (AActor* Actor : AllActors)
    {
        if (Actor == PlayerPawn) continue;

        FString ActorName = Actor->GetName().ToLower();
        // Check if this is a dinosaur (by name convention from other agents)
        bool bIsDino = ActorName.Contains(TEXT("dino")) ||
                       ActorName.Contains(TEXT("trex")) ||
                       ActorName.Contains(TEXT("raptor")) ||
                       ActorName.Contains(TEXT("brach")) ||
                       ActorName.Contains(TEXT("tricera")) ||
                       ActorName.Contains(TEXT("edmonto"));

        if (bIsDino)
        {
            float Dist = FVector::Dist(PlayerLocation, Actor->GetActorLocation());
            ClosestDino = FMath::Min(ClosestDino, Dist);
        }
    }

    NearestDinosaurDistance = ClosestDino;
    DangerIntensity = CalculateDangerIntensity();

    // Auto-set danger level based on proximity
    EAudio_DangerLevel NewLevel = EAudio_DangerLevel::Safe;
    if (ClosestDino < 500.0f)
        NewLevel = EAudio_DangerLevel::Combat;
    else if (ClosestDino < 1200.0f)
        NewLevel = EAudio_DangerLevel::Threatened;
    else if (ClosestDino < 2500.0f)
        NewLevel = EAudio_DangerLevel::Cautious;

    if (NewLevel != CurrentDangerLevel)
    {
        SetDangerLevel(NewLevel);
    }
}

void APrehistoricAudioSystem::UpdateAmbientLayers(float DeltaTime)
{
    // Future: blend between ambient layer assets based on biome + time of day
    // For now, log state changes
}

void APrehistoricAudioSystem::BlendMusicLayers(float DeltaTime)
{
    if (!DangerAudioComponent) return;

    // Target volume based on danger intensity
    float TargetVolume = DangerIntensity;

    // During silence window (pre-attack), cut music to zero
    if (bInSilenceWindow)
    {
        TargetVolume = 0.0f;
    }

    // Smooth blend
    float CurrentVolume = DangerAudioComponent->VolumeMultiplier;
    float NewVolume = FMath::FInterpTo(CurrentVolume, TargetVolume, DeltaTime, MusicTransitionSpeed);
    DangerAudioComponent->SetVolumeMultiplier(NewVolume);
}

float APrehistoricAudioSystem::CalculateDangerIntensity() const
{
    // Map danger level to 0-1 intensity
    switch (CurrentDangerLevel)
    {
        case EAudio_DangerLevel::Safe:       return 0.0f;
        case EAudio_DangerLevel::Cautious:   return 0.25f;
        case EAudio_DangerLevel::Threatened: return 0.6f;
        case EAudio_DangerLevel::Combat:     return 1.0f;
        case EAudio_DangerLevel::Fleeing:    return 0.85f;
        default:                             return 0.0f;
    }
}

void APrehistoricAudioSystem::SetDangerLevel(EAudio_DangerLevel NewLevel)
{
    if (NewLevel == CurrentDangerLevel) return;

    EAudio_DangerLevel OldLevel = CurrentDangerLevel;
    CurrentDangerLevel = NewLevel;
    DangerIntensity = CalculateDangerIntensity();

    UE_LOG(LogTemp, Log, TEXT("PrehistoricAudioSystem: Danger level changed %d -> %d (intensity=%.2f)"),
        (int32)OldLevel, (int32)NewLevel, DangerIntensity);

    // Trigger silence window before escalating to combat (Walter Murch principle)
    if (NewLevel == EAudio_DangerLevel::Combat && OldLevel == EAudio_DangerLevel::Threatened)
    {
        TriggerSilenceWindow(SilenceBeforeAttackSeconds);
    }

    // Trigger stinger on escalation
    if ((int32)NewLevel > (int32)OldLevel)
    {
        TriggerDangerStinger(NewLevel);
    }
}

void APrehistoricAudioSystem::SetTimeOfDay(EAudio_TimeOfDay NewTime)
{
    if (NewTime == CurrentTimeOfDay) return;
    CurrentTimeOfDay = NewTime;

    UE_LOG(LogTemp, Log, TEXT("PrehistoricAudioSystem: Time of day changed to %d"), (int32)NewTime);
}

void APrehistoricAudioSystem::SetBiome(EAudio_BiomeType NewBiome)
{
    if (NewBiome == CurrentBiome) return;
    CurrentBiome = NewBiome;

    UE_LOG(LogTemp, Log, TEXT("PrehistoricAudioSystem: Biome changed to %d"), (int32)NewBiome);
}

void APrehistoricAudioSystem::TriggerDangerStinger(EAudio_DangerLevel Level)
{
    if (DangerStingerCooldown > 0.0f) return;

    // Find matching danger cue
    for (const FAudio_DangerCue& Cue : DangerCues)
    {
        if (Cue.TriggerLevel == Level && Cue.StingerSound)
        {
            if (DangerAudioComponent)
            {
                DangerAudioComponent->SetSound(Cue.StingerSound);
                DangerAudioComponent->Play();
                DangerStingerCooldown = Cue.CooldownSeconds;
                UE_LOG(LogTemp, Log, TEXT("PrehistoricAudioSystem: Playing danger stinger for level %d"), (int32)Level);
            }
            break;
        }
    }
}

void APrehistoricAudioSystem::PlayVoiceLine(const FString& LineID)
{
    for (FAudio_VoiceLine& Line : SurvivorVoiceLines)
    {
        if (Line.LineID == LineID && !Line.bPlayed)
        {
            // In production: load audio from Line.AudioURL and play via VoiceAudioComponent
            // For now, log the subtitle as feedback
            UE_LOG(LogTemp, Log, TEXT("PrehistoricAudioSystem: Voice line [%s]: %s"),
                *LineID, *Line.Subtitle);
            Line.bPlayed = true;
            break;
        }
    }
}

void APrehistoricAudioSystem::TriggerSilenceWindow(float Duration)
{
    bInSilenceWindow = true;
    SilenceWindowTimer = Duration;

    UE_LOG(LogTemp, Log, TEXT("PrehistoricAudioSystem: SILENCE WINDOW triggered for %.1fs (pre-attack tension)"), Duration);
}

void APrehistoricAudioSystem::DebugPrintAudioState()
{
    UE_LOG(LogTemp, Warning, TEXT("=== PrehistoricAudioSystem Debug ==="));
    UE_LOG(LogTemp, Warning, TEXT("  DangerLevel: %d"), (int32)CurrentDangerLevel);
    UE_LOG(LogTemp, Warning, TEXT("  DangerIntensity: %.2f"), DangerIntensity);
    UE_LOG(LogTemp, Warning, TEXT("  NearestDino: %.0f cm"), NearestDinosaurDistance);
    UE_LOG(LogTemp, Warning, TEXT("  TimeOfDay: %d"), (int32)CurrentTimeOfDay);
    UE_LOG(LogTemp, Warning, TEXT("  Biome: %d"), (int32)CurrentBiome);
    UE_LOG(LogTemp, Warning, TEXT("  SilenceWindow: %s (%.1fs)"), bInSilenceWindow ? TEXT("YES") : TEXT("NO"), SilenceWindowTimer);
    UE_LOG(LogTemp, Warning, TEXT("  VoiceLines: %d"), SurvivorVoiceLines.Num());
    UE_LOG(LogTemp, Warning, TEXT("====================================="));
}
