#include "Arch_DwellingSystem.h"
#include "Engine/Engine.h"
#include "Engine/World.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMeshActor.h"
#include "Kismet/GameplayStatics.h"
#include "TranspersonalGame/Core/SharedTypes.h"

UArch_DwellingSystem::UArch_DwellingSystem()
{
    PrimaryComponentTick.bCanEverTick = false;
    
    // Initialize dwelling configurations
    InitializeDwellingTypes();
}

void UArch_DwellingSystem::BeginPlay()
{
    Super::BeginPlay();
    
    UE_LOG(LogTemp, Warning, TEXT("Arch_DwellingSystem: System initialized"));
    
    // Auto-generate dwellings if enabled
    if (bAutoGenerateDwellings)
    {
        GenerateDwellingsInBiomes();
    }
}

void UArch_DwellingSystem::InitializeDwellingTypes()
{
    DwellingConfigurations.Empty();
    
    // Cave Dwelling Configuration
    FArch_DwellingConfig CaveConfig;
    CaveConfig.DwellingType = EArch_DwellingType::Cave;
    CaveConfig.RequiredBiome = EBiomeType::Mountain;
    CaveConfig.BaseScale = FVector(4.0f, 6.0f, 3.0f);
    CaveConfig.MaterialType = EArch_MaterialType::Stone;
    CaveConfig.MaxCapacity = 6;
    CaveConfig.ConstructionTime = 120.0f;
    CaveConfig.DurabilityPoints = 1000.0f;
    CaveConfig.bRequiresFoundation = false;
    DwellingConfigurations.Add(EArch_DwellingType::Cave, CaveConfig);
    
    // Wooden Shelter Configuration
    FArch_DwellingConfig ShelterConfig;
    ShelterConfig.DwellingType = EArch_DwellingType::WoodenShelter;
    ShelterConfig.RequiredBiome = EBiomeType::Forest;
    ShelterConfig.BaseScale = FVector(2.5f, 3.0f, 2.5f);
    ShelterConfig.MaterialType = EArch_MaterialType::Wood;
    ShelterConfig.MaxCapacity = 4;
    ShelterConfig.ConstructionTime = 180.0f;
    ShelterConfig.DurabilityPoints = 500.0f;
    ShelterConfig.bRequiresFoundation = true;
    DwellingConfigurations.Add(EArch_DwellingType::WoodenShelter, ShelterConfig);
    
    // Stilt Platform Configuration
    FArch_DwellingConfig StiltConfig;
    StiltConfig.DwellingType = EArch_DwellingType::StiltPlatform;
    StiltConfig.RequiredBiome = EBiomeType::Swamp;
    StiltConfig.BaseScale = FVector(3.0f, 3.0f, 2.0f);
    StiltConfig.MaterialType = EArch_MaterialType::Wood;
    StiltConfig.MaxCapacity = 3;
    StiltConfig.ConstructionTime = 240.0f;
    StiltConfig.DurabilityPoints = 400.0f;
    StiltConfig.bRequiresFoundation = true;
    DwellingConfigurations.Add(EArch_DwellingType::StiltPlatform, StiltConfig);
    
    // Stone Circle Configuration
    FArch_DwellingConfig CircleConfig;
    CircleConfig.DwellingType = EArch_DwellingType::StoneCircle;
    CircleConfig.RequiredBiome = EBiomeType::Savanna;
    CircleConfig.BaseScale = FVector(8.0f, 8.0f, 0.5f);
    CircleConfig.MaterialType = EArch_MaterialType::Stone;
    CircleConfig.MaxCapacity = 12;
    CircleConfig.ConstructionTime = 300.0f;
    CircleConfig.DurabilityPoints = 800.0f;
    CircleConfig.bRequiresFoundation = false;
    DwellingConfigurations.Add(EArch_DwellingType::StoneCircle, CircleConfig);
    
    // Desert Shelter Configuration
    FArch_DwellingConfig DesertConfig;
    DesertConfig.DwellingType = EArch_DwellingType::DesertShelter;
    DesertConfig.RequiredBiome = EBiomeType::Desert;
    DesertConfig.BaseScale = FVector(2.0f, 2.0f, 1.5f);
    DesertConfig.MaterialType = EArch_MaterialType::Clay;
    DesertConfig.MaxCapacity = 2;
    DesertConfig.ConstructionTime = 150.0f;
    DesertConfig.DurabilityPoints = 300.0f;
    DesertConfig.bRequiresFoundation = true;
    DwellingConfigurations.Add(EArch_DwellingType::DesertShelter, DesertConfig);
}

void UArch_DwellingSystem::GenerateDwellingsInBiomes()
{
    UWorld* World = GetWorld();
    if (!World)
    {
        UE_LOG(LogTemp, Error, TEXT("Arch_DwellingSystem: No valid world found"));
        return;
    }
    
    // Define biome centers based on global memory coordinates
    TArray<FArch_BiomeSpawnData> BiomeData = {
        {EBiomeType::Swamp, FVector(-50000, -45000, 100), EArch_DwellingType::StiltPlatform},
        {EBiomeType::Forest, FVector(-45000, 40000, 0), EArch_DwellingType::WoodenShelter},
        {EBiomeType::Savanna, FVector(0, 0, 0), EArch_DwellingType::StoneCircle},
        {EBiomeType::Desert, FVector(55000, 0, 0), EArch_DwellingType::DesertShelter},
        {EBiomeType::Mountain, FVector(40000, 50000, 500), EArch_DwellingType::Cave}
    };
    
    for (const FArch_BiomeSpawnData& BiomeSpawn : BiomeData)
    {
        SpawnDwellingInBiome(BiomeSpawn.BiomeType, BiomeSpawn.CenterLocation, BiomeSpawn.PreferredDwelling);
    }
    
    UE_LOG(LogTemp, Warning, TEXT("Arch_DwellingSystem: Generated dwellings in all 5 biomes"));
}

AActor* UArch_DwellingSystem::SpawnDwellingInBiome(EBiomeType BiomeType, FVector CenterLocation, EArch_DwellingType DwellingType)
{
    UWorld* World = GetWorld();
    if (!World)
    {
        return nullptr;
    }
    
    // Get dwelling configuration
    FArch_DwellingConfig* Config = DwellingConfigurations.Find(DwellingType);
    if (!Config)
    {
        UE_LOG(LogTemp, Error, TEXT("Arch_DwellingSystem: No configuration found for dwelling type"));
        return nullptr;
    }
    
    // Add random variation within biome
    FVector SpawnLocation = CenterLocation + FVector(
        FMath::RandRange(-3000.0f, 3000.0f),
        FMath::RandRange(-3000.0f, 3000.0f),
        FMath::RandRange(0.0f, 200.0f)
    );
    
    FRotator SpawnRotation = FRotator(0, FMath::RandRange(0.0f, 360.0f), 0);
    
    // Spawn static mesh actor as dwelling placeholder
    AActor* DwellingActor = World->SpawnActor<AStaticMeshActor>(SpawnLocation, SpawnRotation);
    if (DwellingActor)
    {
        // Configure the dwelling
        DwellingActor->SetActorScale3D(Config->BaseScale);
        
        // Set actor label for identification
        FString DwellingName = FString::Printf(TEXT("Arch_%s_%s"), 
            *GetDwellingTypeName(DwellingType),
            *GetBiomeTypeName(BiomeType));
        DwellingActor->SetActorLabel(DwellingName);
        
        // Store dwelling data
        FArch_DwellingInstance NewDwelling;
        NewDwelling.DwellingActor = DwellingActor;
        NewDwelling.DwellingType = DwellingType;
        NewDwelling.BiomeType = BiomeType;
        NewDwelling.Location = SpawnLocation;
        NewDwelling.CurrentCapacity = 0;
        NewDwelling.MaxCapacity = Config->MaxCapacity;
        NewDwelling.DurabilityPoints = Config->DurabilityPoints;
        NewDwelling.bIsConstructed = true;
        
        ActiveDwellings.Add(NewDwelling);
        
        UE_LOG(LogTemp, Warning, TEXT("Arch_DwellingSystem: Spawned %s at %s"), 
            *DwellingName, *SpawnLocation.ToString());
    }
    
    return DwellingActor;
}

FString UArch_DwellingSystem::GetDwellingTypeName(EArch_DwellingType DwellingType) const
{
    switch (DwellingType)
    {
        case EArch_DwellingType::Cave: return TEXT("Cave");
        case EArch_DwellingType::WoodenShelter: return TEXT("WoodenShelter");
        case EArch_DwellingType::StiltPlatform: return TEXT("StiltPlatform");
        case EArch_DwellingType::StoneCircle: return TEXT("StoneCircle");
        case EArch_DwellingType::DesertShelter: return TEXT("DesertShelter");
        default: return TEXT("Unknown");
    }
}

FString UArch_DwellingSystem::GetBiomeTypeName(EBiomeType BiomeType) const
{
    switch (BiomeType)
    {
        case EBiomeType::Swamp: return TEXT("Swamp");
        case EBiomeType::Forest: return TEXT("Forest");
        case EBiomeType::Savanna: return TEXT("Savanna");
        case EBiomeType::Desert: return TEXT("Desert");
        case EBiomeType::Mountain: return TEXT("Mountain");
        default: return TEXT("Unknown");
    }
}

bool UArch_DwellingSystem::CanConstructDwelling(EArch_DwellingType DwellingType, FVector Location, EBiomeType BiomeType) const
{
    const FArch_DwellingConfig* Config = DwellingConfigurations.Find(DwellingType);
    if (!Config)
    {
        return false;
    }
    
    // Check biome compatibility
    if (Config->RequiredBiome != BiomeType)
    {
        return false;
    }
    
    // Check for nearby dwellings (minimum distance)
    for (const FArch_DwellingInstance& Dwelling : ActiveDwellings)
    {
        float Distance = FVector::Dist(Location, Dwelling.Location);
        if (Distance < MinimumDwellingDistance)
        {
            return false;
        }
    }
    
    return true;
}

TArray<FArch_DwellingInstance> UArch_DwellingSystem::GetDwellingsInRadius(FVector Center, float Radius) const
{
    TArray<FArch_DwellingInstance> NearbyDwellings;
    
    for (const FArch_DwellingInstance& Dwelling : ActiveDwellings)
    {
        float Distance = FVector::Dist(Center, Dwelling.Location);
        if (Distance <= Radius)
        {
            NearbyDwellings.Add(Dwelling);
        }
    }
    
    return NearbyDwellings;
}

void UArch_DwellingSystem::UpdateDwellingDurability(AActor* DwellingActor, float DamageAmount)
{
    for (FArch_DwellingInstance& Dwelling : ActiveDwellings)
    {
        if (Dwelling.DwellingActor == DwellingActor)
        {
            Dwelling.DurabilityPoints = FMath::Max(0.0f, Dwelling.DurabilityPoints - DamageAmount);
            
            if (Dwelling.DurabilityPoints <= 0.0f)
            {
                // Dwelling destroyed
                UE_LOG(LogTemp, Warning, TEXT("Arch_DwellingSystem: Dwelling destroyed at %s"), 
                    *Dwelling.Location.ToString());
                
                if (Dwelling.DwellingActor)
                {
                    Dwelling.DwellingActor->Destroy();
                }
            }
            break;
        }
    }
}